### ISSUE TITLE
Add scrutinizer config

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-plugin-cookiecutter#12]
`.scrutinizer.yml`

```
checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - '*/tests/*'
        - '*/external/*'
        - '*/versioneer.py'
        - '*/{{ cookiecutter.repo_name }}/_version.py' 
```

https://scrutinizer-ci.com/docs/configuration
